name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project & tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black ruff
          pip install -e .

      - name: Lint (Black)
        run: black --check .

      - name: Lint (Ruff)
        run: ruff check .

      - name: Tests
        run: pytest --cov=habit_tracker --cov-report=term-missing
